name: ðŸš€ Deploy on production (Dreamhost)

on:
  push:
    branches:
      - production

jobs:
  setup:
    name: ðŸ“‚ Setup
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: ðŸ’Ž setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
  deploy:
    name: ðŸš€ Deploy production
    needs: deploy-ghpages
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”¨ build production
        uses: helaili/jekyll-action@v2
        with:
          build_only: true

      - name: ðŸ” Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: ðŸŽ¯ Adding Known Hosts
        run: ssh-keyscan -H agilebrazil.com >> ~/.ssh/known_hosts
      
      - name: ðŸš€ deploy on production
        run: rsync -zav --progress --delete -e 'ssh -o StrictHostKeyChecking=no' build/ agilebrazil@agilebrazil.com:agilebrazil.com/2021
