name: ðŸš€ Deploy on staging (GH-PAGES)

on:
  push:
    branches:
      - master

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‚ setup
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: ðŸ’Ž setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      #- name: ðŸ”¨ install dependencies & build site
      #  uses: limjh16/jekyll-action-ts@v2
      #  with:
      #    enable_cache: true
      #    custom_opts: 'JEKYLL_ENV=development'
      
      - name: ðŸš€ deploy on gh-pages
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #build_only: true
          jekyll_env: development

      #- name: ðŸš€ deploy on gh-pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./_site

      - name: ðŸ”¨ build staging
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
      
      - name: Install xmllint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass
      
      - name: ðŸ” Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: ðŸŽ¯ Adding Known Hosts
        run: ssh-keyscan -H staging.agilebrazil.com >> ~/.ssh/known_hosts
      
      - name: ðŸš€ deploy on staging
        run: rsync -zav --progress --delete --rsh='sshpass -e ssh -o StrictHostKeyChecking=no' ./_site/ agilebrazil@staging.agilebrazil.com:staging.agilebrazil.com/2021

      #- name: ðŸš€ deploy on staging
      #  uses: burnett01/rsync-deployments@4.1
      #  with:
      #    switches: -avzr --delete
      #    path: ./_site
      #    remote_path: staging.agilebrazil.com/2021
      #    remote_host: staging.agilebrazil.com
      #    remote_user: ${{ secrets.DEPLOY_USER }}
      #    remote_key: ${{ secrets.DEPLOY_KEY }}

      #- name: ðŸš€ deploy on staging
      #  uses: trendyminds/github-actions-rsync@master
      #  with:
      #    RSYNC_OPTIONS: -zav --progress --delete
      #    RSYNC_TARGET: staging.agilebrazil.com/2021
      #    RSYNC_SOURCE: ./_site
      #  env:
      #    SSH_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
      #    SSH_USERNAME: ${{secrets.DEPLOY_USER}}
      #    SSH_HOSTNAME: staging.agilebrazil.com
