name: ðŸš€ Deploy on staging

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: ðŸ“‚ Setup
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: ðŸ’Ž setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
  
  deploy-ghpages:
    name: ðŸš€ Deploy gh-pages
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ deploy on gh-pages
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_env: development
  
  deploy-staging:
    name: ðŸš€ Deploy staging
    needs: deploy-ghpages
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”¨ build staging
        uses: helaili/jekyll-action@v2
        with:
          build_only: true

      - name: ðŸ” Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: ðŸŽ¯ Adding Known Hosts
        run: ssh-keyscan -H staging.agilebrazil.com >> ~/.ssh/known_hosts
      
      - name: ðŸš€ deploy on staging
        run: rsync -zav --progress --delete -e 'ssh -o StrictHostKeyChecking=no' build/ agilebrazil@staging.agilebrazil.com:staging.agilebrazil.com/2021
